### ISSUE TITLE
Internal Server Error when uploading/specify urls

### ISSUE THREAD

**Issue by geneho** [nikhilno1/healthy-or-not#1]
Hi !

I'm currently having internal server errors when I upload or specify urls.
Is it due to my version of fastai/pytorch?

I followed this: https://github.com/nikhilno1/healthy-or-not/blob/master/heroku-deploy.md

Thanks!

**Comment by nikhilno1** [comment]
Did you check in Heroku logs for any application issue/asserts?

**Comment by geneho** [comment]
Hi @nikhilno1 ,

I have only reached the testing in local docker instance , not yet into the Heroku portion.

I modified the existing dockerfile code and rebuild the whole container:

> RUN pip install fastai==1.0.19

which now it works. 

I'm guessing there is some changes in the latest fast.ai .
